FROM debian:latest

ARG TERRAFORM_VERSION=1.3.6

RUN  apt-get update \
  && apt-get install -y wget unzip curl python3 python3-pip ca-certificates curl apt-transport-https lsb-release gnupg\
  && rm -rf /var/lib/apt/lists/* \
  && wget --no-check-certificate -O - https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
   | funzip > /usr/local/bin/terraform && chmod +x /usr/local/bin/terraform \
  && python3 -m pip install azure-cli

WORKDIR /usr/src/app
